/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * vNESFrame.java
 *
 * Created on Dec 7, 2011, 6:31:45 PM
 */
package vnes;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;

/**
 *
 * @author jgauci
 */
public class vNESFrame extends javax.swing.JFrame implements Runnable {
    boolean scale;
    boolean scanlines;
    boolean sound;
    boolean fps;
    boolean stereo;
    boolean timeemulation;
    boolean showsoundbuffer;
    int samplerate;
    int romSize;
    int progress;
    AppletUI gui;
    NES nes;
    ScreenView panelScreen;
    String rom = "";
    Font progressFont;
    Color bgColor = Color.black;
    boolean started = false;


  /** Creates new form vNESFrame */
  public vNESFrame() {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setName("Form"); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 598, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 433, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(vNESFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(vNESFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(vNESFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(vNESFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        vNESFrame frame = new vNESFrame();
    frame.setVisible(true);
    frame.init();
    frame.start();
      }
    });
  }

    public void init() {
        initKeyCodes();
        readParams();
        System.gc();

        gui = new AppletUI(this);
        gui.init(false);

        Globals.appletMode = true;
        Globals.memoryFlushValue = 0x00; // make SMB1 hacked version work.

        nes = gui.getNES();
        nes.enableSound(sound);
        nes.reset();

    }

    public void addScreenView() {
      System.out.println("ADD SCREEN VIEW");

        panelScreen = (ScreenView) gui.getScreenView();
        panelScreen.setFPSEnabled(fps);

        this.setLayout(null);

        if (scale) {
          System.out.println("SCALE");

            if (scanlines) {
                panelScreen.setScaleMode(BufferView.SCALE_SCANLINE);
            } else {
                panelScreen.setScaleMode(BufferView.SCALE_NORMAL);
            }

            this.setSize(512, 480);
            this.setBounds(0, 0, 512, 480);
            panelScreen.setBounds(0, 0, 512, 480);

        } else {

            panelScreen.setBounds(0, 0, 256, 240);

        }

        this.setIgnoreRepaint(true);
        this.add(panelScreen);

    }

    public void start() {

        Thread t = new Thread(this);
        t.start();

    }

    public void run() {

        // Set font to be used for progress display of loading:
        progressFont = new Font("Tahoma", Font.TRUETYPE_FONT | Font.BOLD, 12);

        // Can start painting:
        started = true;

        // Load ROM file:
        System.out.println("vNES 2.14 \u00A9 2006-2011 Jamie Sanders");
        System.out.println("For updates, see www.thatsanderskid.com");
        System.out.println("Use of this program subject to GNU GPL, Version 3.");

        nes.loadRom(rom);

        if (nes.rom.isValid()) {

            // Add the screen buffer:
            addScreenView();

            // Set some properties:
            Globals.timeEmulation = timeemulation;
            nes.ppu.showSoundBuffer = showsoundbuffer;

            // Start emulation:
            //System.out.println("vNES is now starting the processor.");
            nes.getCpu().beginExecution();

        } else {

            // ROM file was invalid.
            System.out.println("vNES was unable to find (" + rom + ").");

        }
        
        System.out.println("ROM LOADED");

    }

    public void stop() {
        nes.stopEmulation();
        System.out.println("vNES has stopped the processor.");
        nes.getPapu().stop();
        this.destroy();

    }

    public void destroy() {

        if (nes != null && nes.getCpu().isRunning()) {
            stop();
        }
        
        if (nes != null) {
            nes.destroy();
        }
        if (gui != null) {
            gui.destroy();
        }

        gui = null;
        nes = null;
        panelScreen = null;
        rom = null;

        System.runFinalization();
        System.gc();

    }

    public void showLoadProgress(int percentComplete) {

        progress = percentComplete;
        paint(getGraphics());

    }
  
  public void paint(Graphics g) {
      System.out.println("PAINTING\n");

        String pad;
        String disp;
        int scrw, scrh;
        int txtw, txth;

        if (!started) {
            return;
        }

        // Get screen size:
        if (scale) {
            scrw = 512;
            scrh = 480;
        } else {
            scrw = 256;
            scrh = 240;
        }

        // Fill background:
        g.setColor(bgColor);
        g.fillRect(0, 0, 512, 512);
        System.out.println("BG FILLED "+scrw+","+scrh);
        if(true)
          return;

        // Prepare text:
        if (progress < 10) {
            pad = "  ";
        } else if (progress < 100) {
            pad = " ";
        } else {
            pad = "";
        }
        disp = "vNES is Loading Game... " + pad + progress + "%";

        // Measure text:
        g.setFont(progressFont);
        txtw = g.getFontMetrics(progressFont).stringWidth(disp);
        txth = g.getFontMetrics(progressFont).getHeight();

        // Display text:
        g.setFont(progressFont);
        g.setColor(Color.white);
        g.drawString(disp, scrw / 2 - txtw / 2, scrh / 2 - txth / 2);
        g.drawString(disp, scrw / 2 - txtw / 2, scrh / 2 - txth / 2);
        g.drawString("vNES \u00A9 2006-2011 Jamie Sanders", 12, 448);
        g.drawString("For updates, visit www.thatsanderskid.com", 12, 464);
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables

    public void readParams() {

        String tmp;

        tmp = "IceHockey.nes";
        if (tmp == null || tmp.equals("")) {
            rom = "vnes.nes";
        } else {
            rom = tmp;
        }

        tmp = "";
        if (tmp == null || tmp.equals("")) {
            scale = true;
        } else {
            scale = tmp.equals("on");
        }

        if (tmp == null || tmp.equals("")) {
            sound = true;
        } else {
            sound = tmp.equals("on");
        }

        if (tmp == null || tmp.equals("")) {
            stereo = true; // on by default
        } else {
            stereo = tmp.equals("on");
        }

        if (tmp == null || tmp.equals("")) {
            scanlines = false;
        } else {
            scanlines = tmp.equals("on");
        }

        if (tmp == null || tmp.equals("")) {
            fps = true;
        } else {
            fps = tmp.equals("on");
        }

        if (tmp == null || tmp.equals("")) {
            timeemulation = true;
        } else {
            timeemulation = tmp.equals("on");
        }

        if (tmp == null || tmp.equals("")) {
            showsoundbuffer = false;
        } else {
            showsoundbuffer = tmp.equals("on");
        }

        /* Controller Setup for Player 1 */

        if (tmp == null || tmp.equals("")) {
            Globals.controls.put("p1_up", "VK_UP");
        } else {
            Globals.controls.put("p1_up", "VK_" + tmp);
        }
        if (tmp == null || tmp.equals("")) {
            Globals.controls.put("p1_down", "VK_DOWN");
        } else {
            Globals.controls.put("p1_down", "VK_" + tmp);
        }
        if (tmp == null || tmp.equals("")) {
            Globals.controls.put("p1_left", "VK_LEFT");
        } else {
            Globals.controls.put("p1_left", "VK_" + tmp);
        }
        if (tmp == null || tmp.equals("")) {
            Globals.controls.put("p1_right", "VK_RIGHT");
        } else {
            Globals.controls.put("p1_right", "VK_" + tmp);
        }
        if (tmp == null || tmp.equals("")) {
            Globals.controls.put("p1_a", "VK_X");
        } else {
            Globals.controls.put("p1_a", "VK_" + tmp);
        }
        if (tmp == null || tmp.equals("")) {
            Globals.controls.put("p1_b", "VK_Z");
        } else {
            Globals.controls.put("p1_b", "VK_" + tmp);
        }
        if (tmp == null || tmp.equals("")) {
            Globals.controls.put("p1_start", "VK_ENTER");
        } else {
            Globals.controls.put("p1_start", "VK_" + tmp);
        }
        if (tmp == null || tmp.equals("")) {
            Globals.controls.put("p1_select", "VK_CONTROL");
        } else {
            Globals.controls.put("p1_select", "VK_" + tmp);
        }

        /* Controller Setup for Player 2 */

        if (tmp == null || tmp.equals("")) {
            Globals.controls.put("p2_up", "VK_NUMPAD8");
        } else {
            Globals.controls.put("p2_up", "VK_" + tmp);
        }
        if (tmp == null || tmp.equals("")) {
            Globals.controls.put("p2_down", "VK_NUMPAD2");
        } else {
            Globals.controls.put("p2_down", "VK_" + tmp);
        }
        if (tmp == null || tmp.equals("")) {
            Globals.controls.put("p2_left", "VK_NUMPAD4");
        } else {
            Globals.controls.put("p2_left", "VK_" + tmp);
        }
        if (tmp == null || tmp.equals("")) {
            Globals.controls.put("p2_right", "VK_NUMPAD6");
        } else {
            Globals.controls.put("p2_right", "VK_" + tmp);
        }
        if (tmp == null || tmp.equals("")) {
            Globals.controls.put("p2_a", "VK_NUMPAD7");
        } else {
            Globals.controls.put("p2_a", "VK_" + tmp);
        }
        if (tmp == null || tmp.equals("")) {
            Globals.controls.put("p2_b", "VK_NUMPAD9");
        } else {
            Globals.controls.put("p2_b", "VK_" + tmp);
        }
        if (tmp == null || tmp.equals("")) {
            Globals.controls.put("p2_start", "VK_NUMPAD1");
        } else {
            Globals.controls.put("p2_start", "VK_" + tmp);
        }
        if (tmp == null || tmp.equals("")) {
            Globals.controls.put("p2_select", "VK_NUMPAD3");
        } else {
            Globals.controls.put("p2_select", "VK_" + tmp);
        }

        if (tmp == null || tmp.equals("")) {
            romSize = -1;
        } else {
            try {
                romSize = Integer.parseInt(tmp);
            } catch (Exception e) {
                romSize = -1;
            }
        }
    }

    public void initKeyCodes() {
        Globals.keycodes.put("VK_SPACE", 32);
        Globals.keycodes.put("VK_PAGE_UP", 33);
        Globals.keycodes.put("VK_PAGE_DOWN", 34);
        Globals.keycodes.put("VK_END", 35);
        Globals.keycodes.put("VK_HOME", 36);
        Globals.keycodes.put("VK_DELETE", 127);
        Globals.keycodes.put("VK_INSERT", 155);
        Globals.keycodes.put("VK_LEFT", 37);
        Globals.keycodes.put("VK_UP", 38);
        Globals.keycodes.put("VK_RIGHT", 39);
        Globals.keycodes.put("VK_DOWN", 40);
        Globals.keycodes.put("VK_0", 48);
        Globals.keycodes.put("VK_1", 49);
        Globals.keycodes.put("VK_2", 50);
        Globals.keycodes.put("VK_3", 51);
        Globals.keycodes.put("VK_4", 52);
        Globals.keycodes.put("VK_5", 53);
        Globals.keycodes.put("VK_6", 54);
        Globals.keycodes.put("VK_7", 55);
        Globals.keycodes.put("VK_8", 56);
        Globals.keycodes.put("VK_9", 57);
        Globals.keycodes.put("VK_A", 65);
        Globals.keycodes.put("VK_B", 66);
        Globals.keycodes.put("VK_C", 67);
        Globals.keycodes.put("VK_D", 68);
        Globals.keycodes.put("VK_E", 69);
        Globals.keycodes.put("VK_F", 70);
        Globals.keycodes.put("VK_G", 71);
        Globals.keycodes.put("VK_H", 72);
        Globals.keycodes.put("VK_I", 73);
        Globals.keycodes.put("VK_J", 74);
        Globals.keycodes.put("VK_K", 75);
        Globals.keycodes.put("VK_L", 76);
        Globals.keycodes.put("VK_M", 77);
        Globals.keycodes.put("VK_N", 78);
        Globals.keycodes.put("VK_O", 79);
        Globals.keycodes.put("VK_P", 80);
        Globals.keycodes.put("VK_Q", 81);
        Globals.keycodes.put("VK_R", 82);
        Globals.keycodes.put("VK_S", 83);
        Globals.keycodes.put("VK_T", 84);
        Globals.keycodes.put("VK_U", 85);
        Globals.keycodes.put("VK_V", 86);
        Globals.keycodes.put("VK_W", 87);
        Globals.keycodes.put("VK_X", 88);
        Globals.keycodes.put("VK_Y", 89);
        Globals.keycodes.put("VK_Z", 90);
        Globals.keycodes.put("VK_NUMPAD0", 96);
        Globals.keycodes.put("VK_NUMPAD1", 97);
        Globals.keycodes.put("VK_NUMPAD2", 98);
        Globals.keycodes.put("VK_NUMPAD3", 99);
        Globals.keycodes.put("VK_NUMPAD4", 100);
        Globals.keycodes.put("VK_NUMPAD5", 101);
        Globals.keycodes.put("VK_NUMPAD6", 102);
        Globals.keycodes.put("VK_NUMPAD7", 103);
        Globals.keycodes.put("VK_NUMPAD8", 104);
        Globals.keycodes.put("VK_NUMPAD9", 105);
        Globals.keycodes.put("VK_MULTIPLY", 106);
        Globals.keycodes.put("VK_ADD", 107);
        Globals.keycodes.put("VK_SUBTRACT", 109);
        Globals.keycodes.put("VK_DECIMAL", 110);
        Globals.keycodes.put("VK_DIVIDE", 111);
        Globals.keycodes.put("VK_BACK_SPACE", 8);
        Globals.keycodes.put("VK_TAB", 9);
        Globals.keycodes.put("VK_ENTER", 10);
        Globals.keycodes.put("VK_SHIFT", 16);
        Globals.keycodes.put("VK_CONTROL", 17);
        Globals.keycodes.put("VK_ALT", 18);
        Globals.keycodes.put("VK_PAUSE", 19);
        Globals.keycodes.put("VK_ESCAPE", 27);
        Globals.keycodes.put("VK_OPEN_BRACKET", 91);
        Globals.keycodes.put("VK_BACK_SLASH", 92);
        Globals.keycodes.put("VK_CLOSE_BRACKET", 93);
        Globals.keycodes.put("VK_SEMICOLON", 59);
        Globals.keycodes.put("VK_QUOTE", 222);
        Globals.keycodes.put("VK_COMMA", 44);
        Globals.keycodes.put("VK_MINUS", 45);
        Globals.keycodes.put("VK_PERIOD", 46);
        Globals.keycodes.put("VK_SLASH", 47);
    }
}
